routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Livewire\Admin\DashboardComponent;
use App\Http\Controllers\Admin\PermissionController;


Route::get('/', function () {
    return view('welcome');
});

// Route::middleware(['auth:sanctum,web', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth:sanctum,web','verified']],function(){
    Route::get('dashboard',DashboardComponent::class)->name('dashboard');

  // Permissions
	Route::resource('permissions', PermissionController::class, ['except' => ['store', 'update', 'destroy']]);

	// Roles
	Route::resource('roles', RoleController::class, ['except' => ['store', 'update', 'destroy']]);

	// Users
	Route::resource('users', UserController::class, ['except' => ['store', 'update', 'destroy']]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use App\Http\Livewire\AdminLoginComponent;
use App\Http\Livewire\UserProfileComponent;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\UserProfileController;


Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('dashboard');
})->name('home');


Route::get('lang/{locale}',function($locale){
    Session::put('locale',$locale);
    return redirect()->back();
});

// Route::middleware(['auth:sanctum,web', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::get('/secure',AdminLoginComponent::class)->name('admin.login');

Route::group(['prefix'=>'','as'=>'','middleware'=>['auth:sanctum,web','verified']],function(){
    Route::get('/dashboard',function(){
        return view('dashboard');
    })->name('dashboard');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => ['auth:sanctum,web']], function () {
    if (file_exists(app_path('Http/Controllers/UserProfileController.php'))) {
        Route::get('/', [UserProfileController::class, 'show'])->name('show');
    }
});

Route::get('user/profile',UserProfileComponent::class)->name('setting.profile');

Route::get('/auth/{provider}',[SocialLoginController::class,'redirectToProvider']);
Route::get('/auth/{provider}/callback',[SocialLoginController::class,'handleProviderCallback']);

app/Models/Admin/Permission.php
<?php

namespace App\Models\Admin;

use DateTimeInterface;
use App\Support\HasAdvancedFilter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Permission extends Model
{
    use HasFactory;
    use HasAdvancedFilter;
    use SoftDeletes;

    public $table = 'permissions';

    public $orderable = [
        'id',
        'title',
    ];

    public $filterable = [
        'id',
        'title',
    ];

    protected $fillable = [
        'title',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use Gate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Admin\Permission;
use App\Http\Controllers\Controller;

class PermissionController extends Controller
{
    public function index()
    {
			abort_if(Gate::denies('permission_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
			return view('admin.permission.index');
    }

    public function create()
    {
      abort_if(Gate::denies('permission_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
			return view('admin.permission.create');
    }

    public function edit(Permission $permission)
    {
			abort_if(Gate::denies('permission_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
			return view('admin.permission.edit', compact('permission'));
    }

    public function show(Permission $permission)
    {
			abort_if(Gate::denies('permission_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');
			return view('admin.permission.show', compact('permission'));
    }
}

app/Http/Livewire/Admin/Permission/CreateComponent.php
<?php

namespace App\Http\Livewire\Admin\Permission;

use Livewire\Component;
use App\Models\Admin\Permission;

class CreateComponent extends Component
{
	public function render()
	{
		return view('livewire.admin.permission.create-component');
	}

	public Permission $permission;

	public function mount(Permission $permission)
	{
			$this->permission = $permission;
	}

	public function submit()
	{
			$this->validate();

			$this->permission->save();

			return redirect()->route('admin.permissions.index');
	}

	protected function rules(): array
	{
			return [
					'permission.title' => [
							'string',
							'required',
					],
					'permission.group' => [
							'string',
							'required',
					],
			];
	}
}

app/Http/Livewire/Admin/Permission/EditComponent.php
<?php

namespace App\Http\Livewire\Admin\Permission;

use Livewire\Component;
use App\Models\Admin\Permission;

class EditComponent extends Component
{
	public Permission $permission;

	public function render()
	{
		return view('livewire.admin.permission.edit-component');
	}

	public function mount(Permission $permission)
	{
			$this->permission = $permission;
	}

	public function submit()
	{
			$this->validate();

			$this->permission->save();

			return redirect()->route('admin.permissions.index');
	}

	protected function rules(): array
	{
			return [
                'permission.title' => [
                    'string',
                    'required',
                ],
                'permission.group' => [
                        'string',
                        'required',
                ],
			];
	}

}

app/Http/Livewire/Admin/Permission/IndexComponent.php
<?php

namespace App\Http\Livewire\Admin\Permission;

use Livewire\Component;
use Livewire\WithPagination;
use Illuminate\Http\Response;
use App\Models\Admin\Permission;
use App\Http\Livewire\WithSorting;
use Illuminate\Support\Facades\Gate;
use App\Http\Livewire\WithConfirmation;

class IndexComponent extends Component
{
	use WithPagination;
	use WithSorting;
	use WithConfirmation;

  protected $paginationTheme = 'bootstrap';

	public int $perPage;

	public array $orderable;

	public string $search = '';

	public array $selected = [];

	public array $paginationOptions;

	public $selectPage = false;

	public $selectAll = false;

	protected $listeners = ['delete','deleteSelected'=>'deleteSelected'];

	protected $queryString = [
			'search' => [
					'except' => '',
			],
			'sortBy' => [
					'except' => 'id',
			],
			'sortDirection' => [
					'except' => 'desc',
			],
	];

  public function updatedSelectPage($value)
	{
		if($value){
			$this->selected = $this->permissions->paginate($this->perPage)->pluck('id')->map(fn ($item) => (string) $item)->toArray();
		} else {
			$this->selected = [];
		}
	}

	public function updatedSelectAll($value)
	{
		if($value){
			$this->selectAll = true;
		} else {
			$this->selectAll = false;
		}
	}

	public function selectAll()
	{
		$this->selectAll = true;
		$this->selected = $this->permissions->pluck('id')->map(fn ($item) => (string) $item)->toArray();
	}

	public function updatedSelected($value)
	{
		if($value){
				$this->selectPage = false;
				$this->selectAll= true;
		} else {
				$this->selectAll=false;
		}
	}

	public function getPermissionsProperty()
	{
		return Permission::advancedFilter([
            's'               => $this->search ?: null,
            'order_column'    => $this->sortBy,
            'order_direction' => $this->sortDirection,
          ]);
	}

    public function render()
	{
		$query = $this->permissions;
		$permissions = $query->paginate($this->perPage);
		return view('livewire.admin.permission.index-component', compact('query', 'permissions', 'permissions'));
	}

	public function getSelectedCountProperty()
	{
		return count($this->selected);
	}

	public function updatingSearch()
	{
		$this->resetPage();
	}

	public function updatingPerPage()
	{
		$this->resetPage();
	}

	public function resetSelected()
	{
		$this->selected = [];
	}

	public function mount()
	{
		$this->sortBy            = 'id';
		$this->sortDirection     = 'asc';
		$this->perPage           = 10;
		$this->paginationOptions = config('project.pagination.options');
		$this->orderable         = (new Permission())->orderable;
	}

	public function deleteSelected()
	{
		abort_if(Gate::denies('permission_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		Permission::whereIn('id', $this->selected)->delete();
		$this->resetSelected();
	}

	public function delete(Permission $permission)
	{
		abort_if(Gate::denies('permission_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$permission->delete();
	}
}

resources/views/livewire/admin/permission/create-component.blade.php
<div>
	<div class="row">
		<div class="col-lg-4">
				<div class="page-header">
						<h4 class="page-title text-primary-d2">
								<a href="{{ route('admin.permissions.index') }}">{{ trans('cruds.permission.title') }}</a>
								<span class="page-info text-secondary-d2 text-80">
										<i class="fa fa-angle-double-right text-80"></i>
										{{ trans('cruds.permission.title_singular') }} {{ trans('global.create') }}
								</span>
						</h4>
				</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-12 col-sm-6 mt-3 mt-sm-0 cards-container">
				<div class="card dcard overflow-hidden">
						<div class="card-header text-white">
								<h5 class="card-title text-primary text-110 pt-1">
										<span><i class="fa fa-user text-105"></i></span>
										{{ trans('global.create') }} {{ trans('cruds.permission.title_singular') }}
								</h5>

								<div class="card-toolbar no-border">
										<a href="#" data-action="toggle" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-default btn-h-outline-default px-15 mx-0 btn-tp">
												<i class="fa fa-chevron-up w-2 mx-1px"></i>
										</a>
								</div>
						</div><!-- /.card-header -->
						<form wire:submit.prevent="submit" class="pt-3">
								<div class="card-body bg-white p-0 collapse show" style="">
										<div class="p-3">
												<div class="form-group">
														<label class="form-control-label">{{ trans('cruds.permission.fields.group') }}: <span class="text-danger">*</span>
																@error('permission.group') <span class="text-danger text-sm">{{ $message }}</span> @enderror
														</label>
														<input wire:model.defer="permission.group" class="form-control" type="text" id="group" value="" placeholder="Enter {{ trans('cruds.permission.fields.group') }}">
												</div>
												<br>
												<div class="form-group {{ $errors->has('permission.title') ? 'invalid' : '' }}">
														<label class="form-label required" for="title">{{ trans('cruds.permission.fields.title') }} <span class="text-danger">*</span>
																														@error('permission.title') <span class="text-danger text-sm">{{ $message }}</span> @enderror
																												</label>
														<input wire:model.defer="permission.title" class="form-control" type="text" name="title" id="title" placeholder="Enter {{ trans('cruds.permission.fields.title') }}">
												</div>
										</div>
								</div><!-- /.card-body -->
								<div class="card-footer bgc-white px-4 py-3 brc-dark-l3 d-flex justify-content-center">
										<a href="{{ route('admin.permissions.index') }}" class="btn border-2 btn-lighter-secondary btn-text-black btn-h-secondary btn-a-secondary btn-bgc-tp">
												<i class="fa fa-times text-110 text-danger-m1 mr-1"></i>
												{{ trans('global.cancel') }}
										</a>
										&nbsp;&nbsp;&nbsp;
										<button type="submit" class="btn border-2 btn-lighter-primary btn-text-black btn-h-primary btn-a-primary btn-bgc-tp">
												<i class="fa fa-check mr-1 text-success"></i>
												{{ trans('global.save') }}
										</button>
								</div><!-- /.card-footer -->
						</form>
				</div><!-- /.card -->
		</div>
	</div>
</div>

resources/views/livewire/admin/permission/edit-component.blade.php
<div>
	<div class="row">
		<div class="col-lg-4">
				<div class="page-header">
						<h4 class="page-title text-primary-d2">
								<a href="{{ route('admin.permissions.index') }}">{{ trans('cruds.permission.title') }}</a>
								<span class="page-info text-secondary-d2 text-80">
										<i class="fa fa-angle-double-right text-80"></i>
										{{ trans('cruds.permission.title_singular') }} {{ trans('global.edit') }}
								</span>
						</h4>
				</div>
		</div>
	</div>

	<div class="row justify-content-center">
    <div class="col-12 col-sm-6 mt-3 mt-sm-0 cards-container">
        <div class="card dcard overflow-hidden">
            <div class="card-header text-white">
                <h5 class="card-title text-primary text-110 pt-1">
                    <span><i class="fa fa-user text-105"></i></span>
                    {{ trans('global.create') }} {{ trans('cruds.permission.title_singular') }}
                </h5>

                <div class="card-toolbar no-border">
                    <a href="#" data-action="toggle" class="card-toolbar-btn btn btn-sm radius-1 btn-outline-default btn-h-outline-default px-15 mx-0 btn-tp">
                        <i class="fa fa-chevron-up w-2 mx-1px"></i>
                    </a>
                </div>
            </div><!-- /.card-header -->
            <form wire:submit.prevent="submit" class="pt-3">
                <div class="card-body bg-white p-0 collapse show" style="">
                    <div class="p-3">
                        <div class="form-group">
                            <label class="form-control-label">{{ trans('cruds.permission.fields.group') }}: <span class="text-danger">*</span>
                                @error('permission.group') <span class="text-danger text-sm">{{ $message }}</span> @enderror
                            </label>
                            <input wire:model.defer="permission.group" class="form-control" type="text" id="group" value="" placeholder="Enter {{ trans('cruds.permission.fields.group') }}">
                        </div>
                        <br>
                        <div class="form-group {{ $errors->has('permission.title') ? 'invalid' : '' }}">
                            <label class="form-label required" for="title">{{ trans('cruds.permission.fields.title') }} <span class="text-danger">*</span>
															@error('permission.title') <span class="text-danger text-sm">{{ $message }}</span> @enderror
														</label>
                            <input wire:model.defer="permission.title" class="form-control" type="text" name="title" id="title" placeholder="Enter {{ trans('cruds.permission.fields.title') }}">
                        </div>
                    </div>
                </div><!-- /.card-body -->
                <div class="card-footer bgc-white px-4 py-3 brc-dark-l3 d-flex justify-content-center">
                    <a href="{{ route('admin.permissions.index') }}" class="btn border-2 btn-lighter-secondary btn-text-black btn-h-secondary btn-a-secondary btn-bgc-tp">
                        <i class="fa fa-times text-110 text-danger-m1 mr-1"></i>
                        {{ trans('global.cancel') }}
                    </a>
                    &nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn border-2 btn-lighter-primary btn-text-black btn-h-primary btn-a-primary btn-bgc-tp">
                        <i class="fa fa-check mr-1 text-success"></i>
                        {{ trans('global.save') }}
                    </button>
                </div><!-- /.card-footer -->
            </form>
        </div><!-- /.card -->
    </div>
	</div>
</div>

resources/views/livewire/admin/permission/index-component.blade.php
<div>
	<div class="row">
		<div class="col-lg-4">
				<div class="page-header">
						<h5 class="page-title text-primary-d2">
							<a href="{{ route('admin.dashboard') }}"><i class="fa fa-home text-80"></i></a>
								<span class="page-info text-secondary-d2 text-80">
										<i class="fa fa-angle-double-right text-80"></i>
										{{ trans('cruds.permission.title_singular') }} {{ trans('global.list') }}
								</span>
						</h5>
				</div>
		</div>
	</div>

	<div class="row mt-3">
			<div class="col-12">
					<div class="card bcard">

							<div class="card-header bgc-info-d1 text-white border-0">
								<h4><span><i class="fas fa-user-secret"></i></span> {{ trans('cruds.permission.title_singular') }} {{ trans('global.list') }}</h4>
								<div class="mb-2 mb-sm-0">
									<a href="{{ route('admin.permissions.create') }}" class="btn btn-blue px-3 d-block w-100 text-95 radius-round border-2 brc-black-tp10">
										<i class="fa fa-plus mr-1"></i>
										{{ trans('global.add') }} <span class="d-sm-none d-md-inline">{{ trans('global.new') }}</span> {{ trans('cruds.permission.title_singular') }}
									</a>
								</div>
							</div>

							<div class="card-body p-0 border-x-1 border-b-1 brc-default-m4 radius-0 overflow-hidden">
								<div class="bootstrap-table bootstrap4">
										<div class="fixed-table-toolbar">
											<div class="columns columns-left float-left search btn-group">
												<span class="d-inline-block text-grey-d2 mt-2">
													Per page:
												</span>
												<select wire:model="perPage" class="ml-3 ace-select no-border angle-down brc-h-blue-m3 w-auto pr-45 text-secondary-d3">
														@foreach($paginationOptions as $value)
															<option value="{{ $value }}">{{ $value }}</option>
														@endforeach
												</select>
											</div>

											<div class="bs-bars float-left">
												<div id="table-toolbar">
												<button wire:click="$emit('deleteAll')" id="remove-btn" class="btn btn-xs p-2 mr-2 bgc-white btn-lighter-red radius-3px"
													@if ($selectPage || $selectAll)
														null
													@else
														disabled
													@endif
												>
												<i class="fa fa-trash-alt text-125 mx-2px"></i> {{ trans('global.bulk_delete') }}({{ count($selected)}})
												</button>
												</div>
											</div>

											<div class="columns columns-left float-left text-nowrap align-self-center align-self-sm-start ">
												{{-- @if(file_exists(app_path('Http/Livewire/ExcelExport.php')))
													<livewire:excel-export model="Permission" format="csv" />
													<livewire:excel-export model="Permission" format="xlsx" />
													<livewire:excel-export model="Permission" format="pdf" />
												@endif --}}
											</div>
											@if ($selectPage)
												<div class="columns columns-left float-left text-nowrap align-self-center align-self-sm-start mt-3 ml-5 ">
													@if ($selectAll)
														<div>
															You have select All <strong>{{ $permissions->total() }}</strong> items.
														</div>
													@else
														<div>
															You have select <strong>{{ count($selected) }}</strong> items, Do you want to Select All
															<strong>{{ $permissions->total() }}</strong>?
															<a href="javascript:void(0)" wire:click="selectAll" class="ml-2">Select All</a>
														</div>
													@endif
												</div>
											@endif
											<div class="columns columns-right btn-group float-right">
													<button class="btn btn-outline-default bgc-white btn-h-light-primary btn-a-outline-primary py-1 px-25 text-95" type="button" name="fullscreen" aria-label="Fullscreen" title="Fullscreen"><i class="fa fa fa-expand"></i>
													</button>

													<div class="keep-open btn-group" title="Columns">
															<button class="btn btn-outline-default bgc-white btn-h-light-primary btn-a-outline-primary py-1 px-25 text-95 dropdown-toggle" type="button" data-toggle="dropdown" aria-label="Columns" title="Columns">
																	<i class="fa fa-th-list text-orange-d1"></i>
																	<span class="caret"></span>
															</button>

															<div class="dropdown-menu dropdown-menu-right">
																	<label class="dropdown-item dropdown-item-marker">
																			<input type="checkbox" data-field="id" value="1" checked="checked"> <span>Product ID</span>
																	</label>
																	<label class="dropdown-item dropdown-item-marker">
																			<input type="checkbox" data-field="name" value="2" checked="checked"> <span>Product Name</span>
																	</label><label class="dropdown-item dropdown-item-marker">
																			<input type="checkbox" data-field="price" value="3" checked="checked"> <span>Price</span>
																	</label>
																	<label class="dropdown-item dropdown-item-marker">
																			<input type="checkbox" data-field="tools" value="4" checked="checked"> <span><i class="fa fa-cog text-secondary-d1 text-130"></i></span>
																	</label>
															</div>
													</div>

													<button class="btn btn-outline-default bgc-white btn-h-light-primary btn-a-outline-primary py-1 px-25 text-95" type="button" name="print" aria-label="Print" title="Print"><i class="fa fa-print text-purple-d1"></i> </button>

													<div class="export btn-group">
														<button class="btn btn-outline-default bgc-white btn-h-light-primary btn-a-outline-primary py-1 px-25 text-95 dropdown-toggle" aria-label="Export" data-toggle="dropdown" type="button" title="Export data"><i class="fa fa-download text-blue"></i>
															<span class="caret"></span>
														</button>
														<div class="dropdown-menu dropdown-menu-right">
															@if(file_exists(app_path('Http/Livewire/ExcelExport.php')))
																	<livewire:excel-export model="Permission" format="csv" />
																	<livewire:excel-export model="Permission" format="xlsx" />
																	<livewire:excel-export model="Permission" format="pdf" />
															@endif
														</div>
												</div>
											</div>

											<div class="columns columns-right float-right search btn-group">
												<input wire:model.debounce.300ms="search" class="form-control search-input" type="search" placeholder="Search" autocomplete="off">
											</div>
										</div>

										<div class="fixed-table-container" style="padding-bottom: 0px;">
											<div class="fixed-table-body">
													<table class="table text-dark-m2 text-95 bgc-white ml-n1px table-bordered table-hover">
															<thead class="bgc-white text-white text-uppercase text-100">
																	<tr class="bgc-info text-white brc-black-tp10">
																			{{-- <th class="detail" style="width: 3%">
																							<div class="fht-cell"></div>
																			</th> --}}
																			<th class="bs-checkbox" style="width: 5%">
																				<div class="th-inner">
																					<label>
																						<input wire:model="selectPage" id="selectPage" name="btSelectAll" type="checkbox"><span></span>
																					</label>
																				</div>
																				<div class="fht-cell"></div>
																			</th>
																			<th style="width: 5%">
																				<div class="th-inner sortable both">
																						{{ trans('cruds.permission.fields.id') }}
																						@include('components.table.sort', ['field' => 'id'])
																				</div>
																				<div class="fht-cell"></div>
																			</th>
																			<th style="width: 10%">
																				<div class="th-inner sortable both">
																					{{ trans('cruds.permission.fields.group') }}
																					@include('components.table.sort', ['field' => 'group'])
																					<div class="fht-cell"></div>
																			</div>
																			</th>
																			<th style="width: 70%">
																				<div class="th-inner sortable both">
																						{{ trans('cruds.permission.title') }} {{ trans('cruds.permission.fields.title') }}
																						@include('components.table.sort', ['field' =>  'title'])
																				</div>
																				<div class="fht-cell"></div>
																			</th>
																			<th style="text-align: center; width: 10% ">
																							<div class="th-inner "><i class="fa fa-cog text-secondary-d1 text-130"></i></div>
																							<div class="fht-cell"></div>
																			</th>
																	</tr>
															</thead>
															<tbody>
																	@forelse($permissions as $permission)
																		<tr>
																			{{-- <td>
																							<a class="detail-icon" href="#">
																							<i class="fa fa-plus text-blue"></i>
																							</a>
																			</td> --}}
																			<td class="bs-checkbox ">
																				<label>
																					<input wire:model="selected" id="selected" value="{{ $permission->id }}" name="btSelectItem" type="checkbox">
																					<span></span>
																				</label>
																			</td>
																			<td>{{ $permission->id }}</td>
																			<td>
																				{{ $permission->group }}
																			</td>
																			<td>{{ $permission->title }}</td>
																			<td>
																				<div class="action-buttons">
																					@can('permission_show', Model::class)
																						<a class="text-blue mx-1" href="{{ route('admin.permissions.show', $permission) }}"><i class="fa fa-search-plus text-105"></i></a>
																					@endcan
																					@can('permission_edit')
																						<a class="text-success mx-1" href="{{ route('admin.permissions.edit', $permission) }}"><i class="fa fa-pencil-alt text-105"></i></a>
																					@endcan
																					@can('permission_delete')
																						<a wire:click="$emit('deleteObject', {{ $permission->id }})" class="text-danger-m1 mx-1"><i class="fa fa-trash-alt text-105"></i></a>
																					@endcan
																				</div>
																			</td>
																		</tr>
																	@empty

																	@endforelse
															</tbody>
													</table>
											</div>
										</div>

										<div class="fixed-table-pagination">
												<div class="float-left pagination-detail">
												</div>
												<div class="float-right pagination">
													{{ $permissions->links() }}
												</div>
										</div>
								</div>
								<div class="clearfix"></div>
							</div>

					</div>
			</div>
	</div>
</div>