routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Livewire\Admin\DashboardComponent;
use App\Http\Controllers\Admin\PermissionController;


Route::get('/', function () {
    return view('welcome');
});

// Route::middleware(['auth:sanctum,web', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth:sanctum,web','verified']],function(){
    Route::get('dashboard',DashboardComponent::class)->name('dashboard');

  // Permissions
	Route::resource('permissions', PermissionController::class, ['except' => ['store', 'update', 'destroy']]);

	// Roles
	Route::resource('roles', RoleController::class, ['except' => ['store', 'update', 'destroy']]);

	// Users
	Route::resource('users', UserController::class, ['except' => ['store', 'update', 'destroy']]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use App\Http\Livewire\AdminLoginComponent;
use App\Http\Livewire\UserProfileComponent;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\UserProfileController;


Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('dashboard');
})->name('home');


Route::get('lang/{locale}',function($locale){
    Session::put('locale',$locale);
    return redirect()->back();
});

// Route::middleware(['auth:sanctum,web', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::get('/secure',AdminLoginComponent::class)->name('admin.login');

Route::group(['prefix'=>'','as'=>'','middleware'=>['auth:sanctum,web','verified']],function(){
    Route::get('/dashboard',function(){
        return view('dashboard');
    })->name('dashboard');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'middleware' => ['auth:sanctum,web']], function () {
    if (file_exists(app_path('Http/Controllers/UserProfileController.php'))) {
        Route::get('/', [UserProfileController::class, 'show'])->name('show');
    }
});

Route::get('user/profile',UserProfileComponent::class)->name('setting.profile');

Route::get('/auth/{provider}',[SocialLoginController::class,'redirectToProvider']);
Route::get('/auth/{provider}/callback',[SocialLoginController::class,'handleProviderCallback']);

app/Models/Admin/User.php
<?php

namespace App\Models\Admin;

use Carbon\Carbon;
use DateTimeInterface;
use App\Models\Province;
use App\Models\Admin\Role;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;
use App\Support\HasAdvancedFilter;
use Illuminate\Support\Facades\Hash;
use Laravel\Jetstream\HasProfilePhoto;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasTeams;
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasAdvancedFilter;
    use SoftDeletes;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'phone',
        'password',
        'deleted_at','province_id','address',
        'profile_photo_path','avatar',
        'social_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    protected $dates = [
        'email_verified_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public $orderable = [
        'id',
        'name',
        'email',
        'email_verified_at',
    ];

    public $filterable = [
        'id',
        'name',
        'email',
        'email_verified_at',
        'roles.title',
    ];

    public function getIsAdminAttribute()
    {
        return $this->roles()->where('title', 'Admin')->exists();
    }

    public function scopeAdmins()
    {
        return $this->whereHas('roles', fn ($q) => $q->where('title', 'Admin'));
    }

    public function getEmailVerifiedAtAttribute($value)
    {
        return $value ? Carbon::createFromFormat('Y-m-d H:i:s', $value)->format(config('project.datetime_format')) : null;
    }

    public function setPasswordAttribute($input)
    {
        if ($input) {
            $this->attributes['password'] = Hash::needsRehash($input) ? Hash::make($input) : $input;
        }
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function province()
    {
        return $this->belongsTo(Province::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Models\Admin\User;
use Illuminate\Http\Response;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('user_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        return view('admin.user.index');
    }

    public function create()
    {
        abort_if(Gate::denies('user_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.user.create');
    }

    public function edit(User $user)
    {
        abort_if(Gate::denies('user_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.user.edit', compact('user'));
    }

    public function show(User $user)
    {
        abort_if(Gate::denies('user_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $user->load('roles');

        return view('admin.user.show', compact('user'));
    }
}

app/Http/Livewire/Admin/User/CreateComponent.php
<?php

namespace App\Http\Livewire\Admin\User;

use Livewire\Component;
use App\Models\Admin\Role;
use App\Models\Admin\User;

class CreateComponent extends Component
{
    public User $user;

    public array $roles = [];

    public string $password = '';

    public array $listsForFields = [];

		public $password_confirmation = '';

    public function mount(User $user)
    {
			$this->user = $user;
			$this->initListsForFields();
    }

    public function render()
    {
        return view('livewire.admin.user.create-component');
    }


    public function submit()
    {
			$this->validate();
			$this->user->password = $this->password;
			$this->user->save();
			$this->user->roles()->sync($this->roles);
			return redirect()->route('admin.users.index');
    }

    protected function rules(): array
    {
			return [
					'user.name' => [
							'string',
							'required',
              'max:50',
					],
					'user.email' => [
							'email:rfc',
							'required',
							'unique:users,email',
					],
					'password' => [
							'string',
							'required',
							'confirmed'
					],
                    'password_confirmation'=>[
                        'string',
                        'required'
                    ],
					'roles' => [
							'required',
							'array',
					],
					'roles.*.id' => [
							'integer',
							'exists:roles,id',
					],
			];
    }

    protected function initListsForFields(): void
    {
        $this->listsForFields['roles'] = Role::pluck('title', 'id')->toArray();
    }
}

app/Http/Livewire/Admin/User/EditComponent.php
<?php

namespace App\Http\Livewire\Admin\User;

use Livewire\Component;
use App\Models\Admin\Role;
use App\Models\Admin\User;

class EditComponent extends Component
{
    public User $user;

    public array $roles = [];

    public string $password = '';

    public array $listsForFields = [];

    public function mount(User $user)
    {
        $this->user  = $user;
        $this->roles = $this->user->roles()->pluck('id')->toArray();
        $this->initListsForFields();
        $this->dispatchBrowserEvent('change-select2', $this->roles);
    }

    public function render()
    {
        return view('livewire.admin.user.edit-component');
    }

    public function submit()
    {
			$this->validate();
			$this->user->password = $this->password;
			$this->user->save();
			$this->user->roles()->sync($this->roles);
			return redirect()->route('admin.users.index');
    }

    protected function rules(): array
    {
        return [
            'user.name' => [
                'string',
                'required',
            ],
            'user.email' => [
                'email:rfc',
                'required',
                'unique:users,email,' . $this->user->id,
            ],
            'password' => [
                'string',
            ],
            'roles' => [
                'required',
                'array',
            ],
            'roles.*.id' => [
                'integer',
                'exists:roles,id',
            ],
        ];
    }

    protected function initListsForFields(): void
    {
        $this->listsForFields['roles'] = Role::pluck('title', 'id')->toArray();
    }
}

app/Http/Livewire/Admin/User/IndexComponent.php
<?php

namespace App\Http\Livewire\Admin\User;

use Livewire\Component;
use App\Models\Admin\User;
use Livewire\WithPagination;
use Illuminate\Http\Response;
use App\Http\Livewire\WithSorting;
use Illuminate\Support\Facades\Gate;
use App\Http\Livewire\WithConfirmation;

class IndexComponent extends Component
{
    use WithPagination;
    use WithSorting;
    use WithConfirmation;

    public int $perPage;

    public array $orderable;

    public string $search = '';

    public array $selected = [];

    public array $paginationOptions;

    public $selectPage = false;

    public $selectAll = false;

    protected $paginationTheme = 'bootstrap';

    protected $listeners = ['delete','deleteSelected'=>'deleteSelected'];

    protected $queryString = [
        'search' => [
            'except' => '',
        ],
        'sortBy' => [
            'except' => 'id',
        ],
        'sortDirection' => [
            'except' => 'desc',
        ],
    ];

    public function updatedSelectPage($value)
    {
			if($value){
				$this->selected = $this->users->paginate($this->perPage)->pluck('id')->map(fn ($item) => (string) $item)->toArray();
			} else {
				$this->selected = [];
			}
    }

    public function updatedSelectAll($value)
    {
			if($value){
				$this->selectAll = true;
			} else {
				$this->selectAll = false;
			}
    }

    public function selectAll()
    {
      $this->selectAll = true;
			$this->selected = $this->users->pluck('id')->map(fn ($item) => (string) $item)->toArray();
    }

    public function updatedSelected($value)
    {
			if($value){
					$this->selectPage = false;
					$this->selectAll= true;
			} else {
					$this->selectAll=false;
			}
    }

    public function getUsersProperty()
    {
			return User::with(['roles'])->advancedFilter([
						's'               => $this->search ?: null,
						'order_column'    => $this->sortBy,
						'order_direction' => $this->sortDirection,
				]);
    }

    public function getSelectedCountProperty()
    {
      return count($this->selected);
    }

    public function updatingSearch()
    {
      $this->resetPage();
    }

    public function updatingPerPage()
    {
      $this->resetPage();
    }

    public function resetSelected()
    {
      $this->selected = [];
    }

    public function mount()
    {
        $this->sortBy            = 'id';
        $this->sortDirection     = 'asc';
        $this->perPage           = 10;
        $this->paginationOptions = config('project.pagination.options');
        $this->orderable         = (new User())->orderable;
    }

    public function render()
    {
        $query =$this->users;
        $users = $query->paginate($this->perPage);
        return view('livewire.admin.user.index-component', compact('query', 'users', 'users'));
    }

    public function deleteSelected()
    {
			abort_if(Gate::denies('user_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
			User::whereIn('id', $this->selected)->delete();
			$this->resetSelected();
    }

    public function delete(User $user)
    {
        abort_if(Gate::denies('user_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $user->delete();
    }
}

resources/views/admin/user/Create.blade.php
@extends('layouts.ace_admin_layout')

@push('styles')

@endpush

@section('admin_content')

    @livewire('admin.user.create-component')

@endsection

@push('scripts')

@endpush

resources/views/admin/user/Edit.blade.php
@extends('layouts.ace_admin_layout')

@section('admin_content')

    @livewire('admin.user.edit-component',[$user])

@endsection

resources/views/admin/user/Index.blade.php
@extends('layouts.ace_admin_layout')

@push('styles')
    {{-- <link rel="stylesheet" href="{{ asset('backend/ace') }}/node_modules/basictable/dist/css/basictable.css"> --}}
    <link rel="stylesheet" href="{{ asset('backend/ace') }}/node_modules/bootstrap-table/dist/bootstrap-table.css">
@endpush

@section('admin_content')

    @livewire('admin.user.index-component')

@endsection

@push('scripts')
  <script src="{{ asset('backend/ace') }}/node_modules/tableexport.jquery.plugin/tableExport.min.js"></script>
  <script src="{{ asset('backend/ace') }}/node_modules/bootstrap-table/dist/bootstrap-table.min.js"></script>
  <script src="{{ asset('backend/ace') }}/node_modules/bootstrap-table/dist/extensions/export/bootstrap-table-export.js"></script>
  <script src="{{ asset('backend/ace') }}/node_modules/bootstrap-table/dist/extensions/print/bootstrap-table-print.js"></script>
  <script src="{{ asset('backend/ace') }}/node_modules/bootstrap-table/dist/extensions/mobile/bootstrap-table-mobile.js"></script>
  {{-- <script src="{{ asset('backend/ace') }}/node_modules/basictable/dist/js/jquery.basictable.js"></script>
	<script>
		jQuery(function($) {
			// highlight simple table row when selected
			function _highlight(row, checked) {
					// `classList.toggle` with 2 arguments isn't supported in IE10+
					// row.classList.toggle('active', checked)
					// row.classList.toggle('bgc-yellow-l3', checked)
					// row.classList.toggle('bgc-h-default-l3', !checked)

					if (checked) {
							row.classList.add('active')
							row.classList.add('bgc-success-l3')
							row.classList.remove('bgc-h-default-l3')
					}
					else {
							row.classList.remove('active')
							row.classList.remove('bgc-success-l3')
							row.classList.add('bgc-h-default-l3')
					}
			}

			$('#simple-table tbody tr')
			.on('click', function(e) {
					var ret = false
					try {
							// return if clicked on a .btn or .dropdown
							ret = e.target.classList.contains('btn') || e.target.parentNode.classList.contains('btn')|| e.target.closest('.dropdown') != null
					} catch(err) {}

					if (ret) return

					var inp = this.querySelector('input')
					if(inp == null) return

					if(e.target.tagName != "INPUT") {
							inp.checked = !inp.checked
					}
					_highlight(this, inp.checked)
			})

			$('#simple-table thead input')
			.on('change', function() {
					var checked = this.checked
					$('#simple-table tbody input[type=checkbox]')
					.each(function() {
							this.checked = checked
							var row = $(this).closest('tr').get(0)
							_highlight(row, checked)
					})
			})

			// responsive table using basic table plugin
			$('#responsive-table').basictable({breakpoint: 800})
			})
	</script> --}}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script>
		Livewire.on('deleteObject',objectId =>{
			Swal.fire({
					title: 'Are you sure?',
					text: "You won't be able to revert this!",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
					if (result.value) {
						Livewire.emitTo('admin.user.index-component','delete',objectId);
						Swal.fire({
							position: 'top-end',
							icon: 'success',
							title: 'Your Data has been deleted',
							showConfirmButton: false,
							timer: 1500
						})
						// toastr.success('YYour Data has been deleted');
					}
			})
		});

		Livewire.on('deleteAll',checkAll => {
			Swal.fire({
					title: 'Are you sure?',
					text: "You won't be able to revert this!",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
					if (result.value) {
						Livewire.emitTo('admin.user.index-component','deleteSelected');
						// toastr.success('YYour Data has been deleted');
						Swal.fire({
							position: 'top-end',
							icon: 'success',
							title: 'Your Data has been deleted',
							showConfirmButton: false,
							timer: 1500
						})
					}
				})
		});
	</script>
@endpush

resources/views/admin/user/Show.blade.php
@extends('layouts.ace_admin_layout')

@section('admin_content')

	<div class="row">
					<div class="col-lg-4">
							<div class="page-header">
									<h4 class="page-title text-primary-d2">
											<a href="{{ route('admin.users.index') }}">{{ trans('cruds.user.title') }}</a>
											<span class="page-info text-secondary-d2 text-80">
													<i class="fa fa-angle-double-right text-80"></i>
													{{ trans('cruds.user.title_singular') }} {{ trans('global.view') }}
											</span>
									</h4>
							</div>
					</div>
	</div>

	<div class="row">
		<div class="col-lg-4">
			<div class="card bg-blueGray-100">
				<div class="card-header">
					<div class="card-header-container">
						<h6 class="card-title">
							{{ trans('global.view') }}
							{{ trans('cruds.user.title_singular') }}:
							{{ trans('cruds.user.fields.id') }}
							{{ $user->id }}
						</h6>
					</div>
				</div>

				<div class="card-body">
						<div class="pt-3">
								<table class="table table-view table-bordered table-striped">
										<tbody class="bg-white">
												<tr>
														<th>
																{{ trans('cruds.user.fields.id') }}
														</th>
														<td>
																{{ $user->id }}
														</td>
												</tr>
												<tr>
														<th>
																{{ trans('cruds.user.fields.name') }}
														</th>
														<td>
																{{ $user->name }}
														</td>
												</tr>
												<tr>
														<th>
																{{ trans('cruds.user.fields.email') }}
														</th>
														<td>
																<a class="link-light-blue" href="mailto:{{ $user->email }}">
																		<i class="far fa-envelope fa-fw">
																		</i>
																		{{ $user->email }}
																</a>
														</td>
												</tr>
												<tr>
														<th>
																{{ trans('cruds.user.fields.email_verified_at') }}
														</th>
														<td>
																{{ $user->email_verified_at }}
														</td>
												</tr>
												<tr>
														<th>
																{{ trans('cruds.user.fields.roles') }}
														</th>
														<td>
																@foreach($user->roles as $key => $entry)
																		<span class="badge badge-relationship">{{ $entry->title }}</span>
																@endforeach
														</td>
												</tr>
										</tbody>
								</table>
						</div>
						<div class="form-group">
								@can('user_edit')
									<a href="{{ route('admin.users.edit', $user) }}" class="btn btn-sm btn-success mr-2">
										<i class="fa fa-edit text-110 text-white-m1 mr-1"></i>{{ trans('global.edit') }}
									</a>
								@endcan
								<a href="{{ route('admin.users.index') }}" class="btn btn-sm btn-secondary">
									<i class="fa fa-times text-110 text-danger-m1 mr-1"></i> {{ trans('global.back') }}
								</a>
						</div>
				</div>
			</div>
		</div>
	</div>

@endsection